CREATE TABLE user(
  uid SERIAL,
  name TEXT,
  page_size INT(20),
  region_1_name TEXT,

  PRIMARY KEY (uid), 
  UNIQUE(name(255)));

CREATE TABLE genomerecord(
  uid SERIAL, 
  name TEXT, 
  species TEXT, 
  strain TEXT, 
  description TEXT, 
  a1 TEXT,
  a1_length INT(20),
  a1_loc TEXT, 
  a2 TEXT,
  a2_length INT(20),
  a2_loc TEXT, 
  overlap VARCHAR(255),
  distance VARCHAR(255),
  sequence LONGTEXT,
  a1_ref BOOL,
  a2_ref BOOL,
  pore TEXT,
  pore_length INT(20),
  pore_loc TEXT,
  pore_within_a2 VARCHAR(255),
  pore_ref BOOL,
  chitinase TEXT,
  chitinase_length INT(20),
  chitinase_loc TEXT,
  chitinase_distance_from_a2 VARCHAR(255),
  chitinase_ref BOOL,
  region1 TEXT,
  region1_length INT(20),
  region1_loc TEXT,
  region2 TEXT,
  region2_length INT(20),
  region2_loc TEXT,
  region3 TEXT,
  region3_length INT(20),
  region3_loc TEXT,
  region4 TEXT,
  region4_length INT(20),
  region4_loc TEXT,
  region1_ref BOOL,
  region2_ref BOOL,
  region3_ref BOOL,
  region4_ref BOOL,

  PRIMARY KEY (uid), 
  UNIQUE(name(255))); 

CREATE TABLE profile_blob(
  uid INT(10) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255),
  a1_profile_ref BOOL,
  a2_profile_ref BOOL,
  pore_profile_ref BOOL,
  chitinase_profile_ref BOOL,
  region1_profile_ref BOOL,
  region2_profile_ref BOOL,
  region3_profile_ref BOOL,
  region4_profile_ref BOOL,
  mimetype VARCHAR(255),
  filename VARCHAR(255),
  profile LONGBLOB,
  size INT(10),
  PRIMARY KEY (uid),
  UNIQUE (name));

CREATE TABLE seqrecord(
  uid SERIAL, 
  name TEXT, 
  species TEXT, 
  description TEXT, 
  sequence LONGTEXT,
  a1_ref BOOL,
  a2_ref BOOL,
  pore_ref BOOL,
  chitinase_ref BOOL,
  region1_ref BOOL,
  region2_ref BOOL,
  region3_ref BOOL,
  region4_ref BOOL,
  PRIMARY KEY (uid), 
  UNIQUE(name(255))); 