from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from Bio.Alphabet import SingleLetterAlphabet
from collections import defaultdict

seq_region_dict = {
    "Proteus_vulgaris": defaultdict(
        None,
        {
            "sequence": "MQNSEKLTFDAPNLPKGGGAVTGLTGNMGAVGPDGAATFSLPLPISQGRGYAPSLGLSYQNQAGNGAFGFGWSVGVMSIRRRTSKGVPTYTQQDEFVGPEGEVIVPIINKKGEIETAQRNELLGVKLAHQYQVTTYRSRIEKSFSRFEYWSLNEANVSANTPKQFWVMLSANGEVHLFGYETTAQIVDSQNSAHIAQWDLNASVSAMGEQIEYHYRAEDEQGCDKQEIQSHKNANTQRYLEKVYYGNPVGERAFSCTKTDNTLPKNALFTLVFDYGERDSALATYPQWQSNSAWALRKDCFSLFHYGFEVRTRRLCRQVLMYHRLESLEKQTPLAETPELVARLTLTYDESASGTVLVSAQKSAFNNNKDAQSLVTLPPVKFDWQMVGATKQAQWQSLDELASFTPQQPYQYVDLLGEGLSGVLYQDRGAWWYRAPVRKEDKQNPNAITWDKAKKLPVIPSLRNSAMLTDVTGNGKLEWLVTQGDVNGYYTQDETNAENWLNFVPLDALPVEYFHSRAEITSLTGSGFADLALIGPRSIRLYAGSAQGWKKSKDIMQADGVTLPIKNVNRRTLVAFSDVLGSGQQHLIKVDYQGVTCWVHLGEGRFSTPMTIPGFSADRLKFNPNQFYLADLDGSGTTDIIYAQSTHLEVYFNQSGNQFVRGDDIALPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQNKKPWLLTSINNNMGLIQNLHYRSSAQYWLDEKSTRQQQNKAKAVSHLPFALHTLWKIETIDEITQSCLAQTYNYRHGVWDGEENEFRGFGCVEATNAESFKSEENTTDKTPSALTRQWFLTGKSLVDNQFFNEFWQGDSAAFSHFSPRFTQGDGSSEKACNNTVH*EHTYWLERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVESRDYHYERIASDPACHQHIILEQDGYGFVSKAVSINYPRRAKGAKNPYQHYESLPETLWASSYDEQQHTLRLGLSRQTCHHLVHPEKQVYQLAIINASRQDSWIFGAEKQPKEGLNVEALLANNNLLTQKSASVFVGQQQLAYLDASGNATLAEPDFPVRLAYSETAELDEETAKVISQPYPDLKLDEVMKNAGYQQKDYLFADETEKSKKLWVKPLLGFKTYGSLAQFYKPLVYKKTEFSCDYNLLWDKQFCVLMGKGSPLNTQDFHLTYDWRFLSPNSITDENKNLRQVTFDGFGRVTTTRFSGAEKGQESGYSHKAFTMPNTVDEALVLTSTLPIATGFVYVTDSWMSSSSKLPPHALQIMTDRYDSDSQQQIRQQIAFSDGFGRLLQTSIRVEAGESFLRSKKGELVVDSVQQAQQKSTTTRWAILGETEYDNKGNVKRVYQPYFLNDWRYVSESSSQPNRFADTHYYDALGRLYQVITAKQYRRHTMMTPWFVAQEDENDTLV",
            "32:325": SeqRecord(
                seq=Seq("PDGAATFSLPLPISQGRGYAPSLGLSYQNQAGNGAFGFGWSVGVMSIRRRTSKG...HRL"),
                id="NZ_KN150746.1_Proteus_vulgaris_TcB_expanded_1443146_1447475_backward_region_name=SpvB",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "881:1022": SeqRecord(
                seq=Seq("LERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVE...PEK"),
                id="NZ_KN150746.1_Proteus_vulgaris_TcB_expanded_1443146_1447475_backward_region_name=TcdB_toxin_midC",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "657:832": SeqRecord(
                seq=Seq("QFVRGDDIALPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQNK...LTG"),
                id="NZ_KN150746.1_Proteus_vulgaris_TcB_expanded_1443146_1447475_backward_region_name=TcdB_toxin_midN",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
        },
    ),
    "NZ_KE166455.1_Pseudomonas_plecoglossicida_TcB_expanded_1153116_1157454_backward": defaultdict(
        None,
        {
            "sequence": "MTDLSVTPAGASGEPVFSPPALPKGGGTVSAGGGMLSVGSADGAAGWSLPLPLPVGRELSPSLSLGYRSSAGNGAFGAGWHCSPPAICRMDRLGIPRYTSSDRWQGPDGEEILLDKGAPRQVASLPFSDVPAVHTVTAWVPRSGGRDQRLEHWRVQTRPDSPGFWLQYHADGSITLFGWSASARVAEPGTPSHVACWYAEETVSATGEHVVYRYRSEDQAGCDEHERAMHPQVANTYLVAVHAMNATSRLALLIPDQAFREDDFMTVMQLDYGERGVDVNTPPAFAAQTPWAVRQDCFSYWRWGFDKRVRRLCREVLLWHRTRMMAGQQDPRPELVSRLHLEYDASGVASVLVAAQQVAYDADGTPQSLPPVEFEPSRPGRAHPAWEALPDLEGFSAPHWQIADLLGEGLPGLLYQDAGAWLYRAPQRDGDAGGDAVTWGPAQALPGAPRPGTGVLADLDGDGQPQWLVNLPGLRGSFTLAPDGQWRDFIAADALPSELAHGAAQLVDLTGDGLQDLVMIGPRSVRLSPRVRGTGWQPAQDISPGPTLPLVGGEHRLVAFADLAGTGLQQWVEVTGEGVTYWPMLGHGRFANPVRMPGFAIEQFNASRVLLGDTDGSGTTDLLYVEPDRIRVFVSHNGNRLVEAEPLAAPEGVVLDATCKLQLVDLRGQGTAELVLSVPHVVPRSWVYRFNDRRPWLLAEVCSNTGSRTLFDYRSSAQCWLDEKLDLQRQGRKAVSRLPFPVHAVSQVTTVDDISGLRTVSGMCYRCAVWDPVEREFRGFMQAVQTDTLSDAQGTAAERSPPAQVRQWFLSGVEAPDSLPAQGFAGPRSAELDFALQATRFTRLDGDRDVPYEPQGAARRWLLRALRGARVRSETYGLDGSERADVPYSIERQRWQVRVYETARADRPAALVTAVETLALSTERIAEDPRITQSLILRQDRRGHVLQHAQVHYPRRAVLSPSPYPVSLPEGLEADARDPQQDTLWLSVWRHRVHHLENGHDHHSGLLEATRSDVLAVPAHALPPGGFSVEHLLAPGSPLEGLADATLTGYQRQQWCDAQGQLSPLPTRQALVAYREIAVLEQATLALLEASLSPQEAAQWHANGGHHLVSLVEDGKRVYVSRHELARHHGPQLFHRLATLRDNEQVGELRIDWSPHAVQVSRLVDAAGLETTVRHDWRFLTPVALTDANDNLHEVTLDALGRVAQTRFQGTEHGQPAGYRSGKVFTVPMAMEGFLALKGGEVPVATAHRVVSDSWMPRARDRQGRPLAGRMGELAQRRLLKAGHLPAIDPHDEREPPHIISLQTDRYNGDSAQQVRLNVTYSDGAGRLLQTAVLSEPGDALVRNSAGGLERDATGAALIQPAQRRWAVSGKTEFDNKGQPVRTWLPYYLDDWRHVQDDSARAGLYADTHLYDALGRVRRVLTAAGRQRRTHYYPWFTVAEDENDTA",
            "40:321": SeqRecord(
                seq=Seq("ADGAAGWSLPLPLPVGRELSPSLSLGYRSSAGNGAFGAGWHCSPPAICRMDRLG...WHR"),
                id="NZ_KE166455.1_Pseudomonas_plecoglossicida_TcB_expanded_1153116_1157454_backward_region_name=SpvB",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "861:1001": SeqRecord(
                seq=Seq("LLRALRGARVRSETYGLDGSERADVPYSIERQRWQVRVYETARADRPAALVTAV...GHD"),
                id="NZ_KE166455.1_Pseudomonas_plecoglossicida_TcB_expanded_1153116_1157454_backward_region_name=TcdB_toxin_midC",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "649:794": SeqRecord(
                seq=Seq("PEGVVLDATCKLQLVDLRGQGTAELVLSVPHVVPRSWVYRFNDRRPWLLAEVCS...AQG"),
                id="NZ_KE166455.1_Pseudomonas_plecoglossicida_TcB_expanded_1153116_1157454_backward_region_name=TcdB_toxin_midN",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
        },
    ),
    "NZ_LXEN01000293.1_Cosenzaea_myxofaciens_TcB_expanded_1443394_1447717_backward": defaultdict(
        None,
        {
            "sequence": "MQNSEKLSFDAPNLPKGGGAVTGLTGNMGAVGPDGAAIFSLPLPISQGRGYAPTLGLTYHNQSGNGEFGFGWSVGVMSIRRRTSKGVPSYSQQDEFIGPEGEVLVPIINKKGKIETAQRNELLGVKLAHQYQVTTYRSRIEKSFSRFEYWSLNEANVSANTPKQFWVMLSANGEVHLFGYETTAQIVDSQNSTHVAQWNLNASVSAMGEQIEYHYRAEDEQGCDPHEIQSHPNANTQRYLDKVYYGNPVGERAFPCTKTDNTLPKNALFTLVFDYGERSNALAAYPQWQSNSAWALRKDCFSLFHYGFEVRTRRLCRQVLMYHRLESLEKQTPLAETPELVARLTLTYYESASGTVLVSAQKSAFNNNKDAQSLVTLPPVKFDWQMVGATKQAQWQSLDELASFTPQQPYQYVDLLGEGLSGVLYQDSGAWWYRAPVRKEDKQNPNAITWDNPKKLPVIPSLRGSAMLTDVTGNGKLEWLVTQGDVRGYYTQDETNAGNWLNFVPLDAIPVEYFHPRAELTSLTGSGFADLALIGPRSIRFYAGSAQGWKSSKEIMQAEGVTLPIKNINRRALVAFSDVLGSGQQHLIKIDYQGVTCWVHCGDGKFNSPITIPGFSADRMRFNPSQLYLADLDGSGTTDIIYIQSTHLEVYFNQSGNQFVRGDDIPLPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQSNKPWLLTSINNNMGLIQNLHYRSSAQYWLDEKSTRQQQNKAKAVSHLPFALHTLWKIETIDEITQSCLAQTYNYRYGVWDGKEKEFRGFGCVEATNAESFKSEENTTDKTPSALTRQWFSTGKTTVDAQFYDEFWQGDSAAFSHFSPRFTQGDGTSEKACNNTVHQEHTYWLERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVESRDYHYERIASDPACHQHIILEQDGYGFVTKTVSINYPRRSKGTINPYQHYESLPETLWASSYDDQQHTLHLSLSRQTCHHIDHPARQIYQLGVTATTRQDIWTYGAEKQPKDGLSVEALLATNNLLTQKSVFAGQQQLAYMDANGRATLLEPDFPARLAYSESAELDEETAKTISQPYPDLKLDDAMKNAGYQQKEYVFADETEKGKKLWVKSLLGVKAYGSLAQFYKPLVYKKTELSCDYNLLWDKQFCVLMGKGSPLNTQDFHLTYDWRFLSPNSITDENKNLRQVTFDGFGRVTTTRFSGTEKGQESGYSHKAFTMPNTVDEALVLTSTLPIATGFVYVTDSWMSSSSKLPPHALQIMTDRYDSDPQQQIRQQIAFSDGFGRLLQTSVRVEAGDVFLRSEKGILAIDSAQQVQQKSTTTRWAISGETEYDNKGNIKRIYQPYFLNDWRYVSDHSAQPHRFADIHYYDALGRLYEVITAKNYRRHTIITPWFTAQADENDTLT",
            "32:325": SeqRecord(
                seq=Seq("PDGAAIFSLPLPISQGRGYAPTLGLTYHNQSGNGEFGFGWSVGVMSIRRRTSKG...HRL"),
                id="NZ_LXEN01000293.1_Cosenzaea_myxofaciens_TcB_expanded_1443394_1447717_backward_region_name=SpvB",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "881:1022": SeqRecord(
                seq=Seq("LERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVE...PAR"),
                id="NZ_LXEN01000293.1_Cosenzaea_myxofaciens_TcB_expanded_1443394_1447717_backward_region_name=TcdB_toxin_midC",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "659:832": SeqRecord(
                seq=Seq("VRGDDIPLPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQSNKP...STG"),
                id="NZ_LXEN01000293.1_Cosenzaea_myxofaciens_TcB_expanded_1443394_1447717_backward_region_name=TcdB_toxin_midN",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
        },
    ),
}

# Shorter names
ABC_3_seqs_1_region = {
    "Proteus_vulgaris": defaultdict(
        None,
        {
            "sequence": "MQNSEKLTFDAPNLPKGGGAVTGLTGNMGAVGPDGAATFSLPLPISQGRGYAPSLGLSYQNQAGNGAFGFGWSVGVMSIRRRTSKGVPTYTQQDEFVGPEGEVIVPIINKKGEIETAQRNELLGVKLAHQYQVTTYRSRIEKSFSRFEYWSLNEANVSANTPKQFWVMLSANGEVHLFGYETTAQIVDSQNSAHIAQWDLNASVSAMGEQIEYHYRAEDEQGCDKQEIQSHKNANTQRYLEKVYYGNPVGERAFSCTKTDNTLPKNALFTLVFDYGERDSALATYPQWQSNSAWALRKDCFSLFHYGFEVRTRRLCRQVLMYHRLESLEKQTPLAETPELVARLTLTYDESASGTVLVSAQKSAFNNNKDAQSLVTLPPVKFDWQMVGATKQAQWQSLDELASFTPQQPYQYVDLLGEGLSGVLYQDRGAWWYRAPVRKEDKQNPNAITWDKAKKLPVIPSLRNSAMLTDVTGNGKLEWLVTQGDVNGYYTQDETNAENWLNFVPLDALPVEYFHSRAEITSLTGSGFADLALIGPRSIRLYAGSAQGWKKSKDIMQADGVTLPIKNVNRRTLVAFSDVLGSGQQHLIKVDYQGVTCWVHLGEGRFSTPMTIPGFSADRLKFNPNQFYLADLDGSGTTDIIYAQSTHLEVYFNQSGNQFVRGDDIALPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQNKKPWLLTSINNNMGLIQNLHYRSSAQYWLDEKSTRQQQNKAKAVSHLPFALHTLWKIETIDEITQSCLAQTYNYRHGVWDGEENEFRGFGCVEATNAESFKSEENTTDKTPSALTRQWFLTGKSLVDNQFFNEFWQGDSAAFSHFSPRFTQGDGSSEKACNNTVH*EHTYWLERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVESRDYHYERIASDPACHQHIILEQDGYGFVSKAVSINYPRRAKGAKNPYQHYESLPETLWASSYDEQQHTLRLGLSRQTCHHLVHPEKQVYQLAIINASRQDSWIFGAEKQPKEGLNVEALLANNNLLTQKSASVFVGQQQLAYLDASGNATLAEPDFPVRLAYSETAELDEETAKVISQPYPDLKLDEVMKNAGYQQKDYLFADETEKSKKLWVKPLLGFKTYGSLAQFYKPLVYKKTEFSCDYNLLWDKQFCVLMGKGSPLNTQDFHLTYDWRFLSPNSITDENKNLRQVTFDGFGRVTTTRFSGAEKGQESGYSHKAFTMPNTVDEALVLTSTLPIATGFVYVTDSWMSSSSKLPPHALQIMTDRYDSDSQQQIRQQIAFSDGFGRLLQTSIRVEAGESFLRSKKGELVVDSVQQAQQKSTTTRWAILGETEYDNKGNVKRVYQPYFLNDWRYVSESSSQPNRFADTHYYDALGRLYQVITAKQYRRHTMMTPWFVAQEDENDTLV",
            "32:325": SeqRecord(
                seq=Seq("PDGAATFSLPLPISQGRGYAPSLGLSYQNQAGNGAFGFGWSVGVMSIRRRTSKG...HRL"),
                id="Proteus_vulgaris_region_name=SpvB",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "881:1022": SeqRecord(
                seq=Seq("LERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVE...PEK"),
                id="Proteus_vulgaris_region_name=TcdB_toxin_midC",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "657:832": SeqRecord(
                seq=Seq("QFVRGDDIALPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQNK...LTG"),
                id="Proteus_vulgaris_region_name=TcdB_toxin_midN",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
        },
    ),
    "Pseudomonas_plecoglossicida": defaultdict(
        None,
        {
            "sequence": "MTDLSVTPAGASGEPVFSPPALPKGGGTVSAGGGMLSVGSADGAAGWSLPLPLPVGRELSPSLSLGYRSSAGNGAFGAGWHCSPPAICRMDRLGIPRYTSSDRWQGPDGEEILLDKGAPRQVASLPFSDVPAVHTVTAWVPRSGGRDQRLEHWRVQTRPDSPGFWLQYHADGSITLFGWSASARVAEPGTPSHVACWYAEETVSATGEHVVYRYRSEDQAGCDEHERAMHPQVANTYLVAVHAMNATSRLALLIPDQAFREDDFMTVMQLDYGERGVDVNTPPAFAAQTPWAVRQDCFSYWRWGFDKRVRRLCREVLLWHRTRMMAGQQDPRPELVSRLHLEYDASGVASVLVAAQQVAYDADGTPQSLPPVEFEPSRPGRAHPAWEALPDLEGFSAPHWQIADLLGEGLPGLLYQDAGAWLYRAPQRDGDAGGDAVTWGPAQALPGAPRPGTGVLADLDGDGQPQWLVNLPGLRGSFTLAPDGQWRDFIAADALPSELAHGAAQLVDLTGDGLQDLVMIGPRSVRLSPRVRGTGWQPAQDISPGPTLPLVGGEHRLVAFADLAGTGLQQWVEVTGEGVTYWPMLGHGRFANPVRMPGFAIEQFNASRVLLGDTDGSGTTDLLYVEPDRIRVFVSHNGNRLVEAEPLAAPEGVVLDATCKLQLVDLRGQGTAELVLSVPHVVPRSWVYRFNDRRPWLLAEVCSNTGSRTLFDYRSSAQCWLDEKLDLQRQGRKAVSRLPFPVHAVSQVTTVDDISGLRTVSGMCYRCAVWDPVEREFRGFMQAVQTDTLSDAQGTAAERSPPAQVRQWFLSGVEAPDSLPAQGFAGPRSAELDFALQATRFTRLDGDRDVPYEPQGAARRWLLRALRGARVRSETYGLDGSERADVPYSIERQRWQVRVYETARADRPAALVTAVETLALSTERIAEDPRITQSLILRQDRRGHVLQHAQVHYPRRAVLSPSPYPVSLPEGLEADARDPQQDTLWLSVWRHRVHHLENGHDHHSGLLEATRSDVLAVPAHALPPGGFSVEHLLAPGSPLEGLADATLTGYQRQQWCDAQGQLSPLPTRQALVAYREIAVLEQATLALLEASLSPQEAAQWHANGGHHLVSLVEDGKRVYVSRHELARHHGPQLFHRLATLRDNEQVGELRIDWSPHAVQVSRLVDAAGLETTVRHDWRFLTPVALTDANDNLHEVTLDALGRVAQTRFQGTEHGQPAGYRSGKVFTVPMAMEGFLALKGGEVPVATAHRVVSDSWMPRARDRQGRPLAGRMGELAQRRLLKAGHLPAIDPHDEREPPHIISLQTDRYNGDSAQQVRLNVTYSDGAGRLLQTAVLSEPGDALVRNSAGGLERDATGAALIQPAQRRWAVSGKTEFDNKGQPVRTWLPYYLDDWRHVQDDSARAGLYADTHLYDALGRVRRVLTAAGRQRRTHYYPWFTVAEDENDTA",
            "40:321": SeqRecord(
                seq=Seq("ADGAAGWSLPLPLPVGRELSPSLSLGYRSSAGNGAFGAGWHCSPPAICRMDRLG...WHR"),
                id="Pseudomonas_plecoglossicida_region_name=SpvB",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "861:1001": SeqRecord(
                seq=Seq("LLRALRGARVRSETYGLDGSERADVPYSIERQRWQVRVYETARADRPAALVTAV...GHD"),
                id="Pseudomonas_plecoglossicida_region_name=TcdB_toxin_midC",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "649:794": SeqRecord(
                seq=Seq("PEGVVLDATCKLQLVDLRGQGTAELVLSVPHVVPRSWVYRFNDRRPWLLAEVCS...AQG"),
                id="Pseudomonas_plecoglossicida_region_name=TcdB_toxin_midN",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
        },
    ),
    "Cosenzaea_myxofaciens": defaultdict(
        None,
        {
            "sequence": "MQNSEKLSFDAPNLPKGGGAVTGLTGNMGAVGPDGAAIFSLPLPISQGRGYAPTLGLTYHNQSGNGEFGFGWSVGVMSIRRRTSKGVPSYSQQDEFIGPEGEVLVPIINKKGKIETAQRNELLGVKLAHQYQVTTYRSRIEKSFSRFEYWSLNEANVSANTPKQFWVMLSANGEVHLFGYETTAQIVDSQNSTHVAQWNLNASVSAMGEQIEYHYRAEDEQGCDPHEIQSHPNANTQRYLDKVYYGNPVGERAFPCTKTDNTLPKNALFTLVFDYGERSNALAAYPQWQSNSAWALRKDCFSLFHYGFEVRTRRLCRQVLMYHRLESLEKQTPLAETPELVARLTLTYYESASGTVLVSAQKSAFNNNKDAQSLVTLPPVKFDWQMVGATKQAQWQSLDELASFTPQQPYQYVDLLGEGLSGVLYQDSGAWWYRAPVRKEDKQNPNAITWDNPKKLPVIPSLRGSAMLTDVTGNGKLEWLVTQGDVRGYYTQDETNAGNWLNFVPLDAIPVEYFHPRAELTSLTGSGFADLALIGPRSIRFYAGSAQGWKSSKEIMQAEGVTLPIKNINRRALVAFSDVLGSGQQHLIKIDYQGVTCWVHCGDGKFNSPITIPGFSADRMRFNPSQLYLADLDGSGTTDIIYIQSTHLEVYFNQSGNQFVRGDDIPLPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQSNKPWLLTSINNNMGLIQNLHYRSSAQYWLDEKSTRQQQNKAKAVSHLPFALHTLWKIETIDEITQSCLAQTYNYRYGVWDGKEKEFRGFGCVEATNAESFKSEENTTDKTPSALTRQWFSTGKTTVDAQFYDEFWQGDSAAFSHFSPRFTQGDGTSEKACNNTVHQEHTYWLERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVESRDYHYERIASDPACHQHIILEQDGYGFVTKTVSINYPRRSKGTINPYQHYESLPETLWASSYDDQQHTLHLSLSRQTCHHIDHPARQIYQLGVTATTRQDIWTYGAEKQPKDGLSVEALLATNNLLTQKSVFAGQQQLAYMDANGRATLLEPDFPARLAYSESAELDEETAKTISQPYPDLKLDDAMKNAGYQQKEYVFADETEKGKKLWVKSLLGVKAYGSLAQFYKPLVYKKTELSCDYNLLWDKQFCVLMGKGSPLNTQDFHLTYDWRFLSPNSITDENKNLRQVTFDGFGRVTTTRFSGTEKGQESGYSHKAFTMPNTVDEALVLTSTLPIATGFVYVTDSWMSSSSKLPPHALQIMTDRYDSDPQQQIRQQIAFSDGFGRLLQTSVRVEAGDVFLRSEKGILAIDSAQQVQQKSTTTRWAISGETEYDNKGNIKRIYQPYFLNDWRYVSDHSAQPHRFADIHYYDALGRLYEVITAKNYRRHTIITPWFTAQADENDTLT",
            "32:325": SeqRecord(
                seq=Seq("PDGAAIFSLPLPISQGRGYAPTLGLTYHNQSGNGEFGFGWSVGVMSIRRRTSKG...HRL"),
                id="Cosenzaea_myxofaciens_region_name=SpvB",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "881:1022": SeqRecord(
                seq=Seq("LERGLQGQLLRKEVYGLDNTVVSDVPYVVTEQRPQVRLIEAQGRSPVVMPSVVE...PAR"),
                id="Cosenzaea_myxofaciens_region_name=TcdB_toxin_midC",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
            "659:832": SeqRecord(
                seq=Seq("VRGDDIPLPKGVRFDNQCQLQVADIQGLGVASILLTKAYPTPQHWVLSLQSNKP...STG"),
                id="Cosenzaea_myxofaciens_region_name=TcdB_toxin_midN",
                name="<unknown name>",
                description="",
                dbxrefs=[],
            ),
        },
    ),
}

rd = {'TcC_expanded': {'NZ_CBXE010000496.1': SeqRecord(
    seq=Seq('MAQTLYSKTPSVVVMDNRGLNVRTVQYYRHPDTVDFTDERISFSQYTLAGFPER...SFA', SingleLetterAlphabet()),
    id='NZ_CBXE010000496.1', name='NZ_CBXE010000496.1',
    description='NZ_CBXE010000496.1 Xenorhabdus_cabanillasii_TcC_expanded_1015925_1019078_backward', dbxrefs=[]),
                       'NZ_KB372811.1': SeqRecord(
                           seq=Seq('MSSPDYTLYRGTPAVAVQDNRGLIVREIAYHRHPDQSGETDTRITRYQFSARGF...LKF',
                                   SingleLetterAlphabet()), id='NZ_KB372811.1', name='NZ_KB372811.1',
                           description='NZ_KB372811.1 Erwinia_toletana_TcC_expanded_3258335_3261272_backward',
                           dbxrefs=[])}, 'TcB_expanded': {'NZ_CBXE010000496.1': SeqRecord(
    seq=Seq('MQSSKDLKLEMPSLPKGGGALYGMGESLGAIGPDGLASFSLPLPVSGGRGVAPA...VNQ', SingleLetterAlphabet()),
    id='NZ_CBXE010000496.1', name='NZ_CBXE010000496.1',
    description='NZ_CBXE010000496.1 Xenorhabdus_cabanillasii_TcB_expanded_1019132_1023545_backward', dbxrefs=[]),
                                                          'NZ_KB372811.1': SeqRecord(seq=Seq(
                                                              'MQTTEALRLNPPSLPSGGGAISGLKSDTPVAAPDGAASLSIALPVSSGRGYAPA...ETS',
                                                              SingleLetterAlphabet()), id='NZ_KB372811.1',
                                                                                     name='NZ_KB372811.1',
                                                                                     description='NZ_KB372811.1 Erwinia_toletana_TcB_expanded_3261274_3265618_backward',
                                                                                     dbxrefs=[])}, 'TcdA1': {
    'NZ_KB372811.1': SeqRecord(
        seq=Seq('LAMLQLNKLIRFSKAGGMAAADIWRVIASNNNQFNITDAIVSQLLWIQYYCQYY...YTI', SingleLetterAlphabet()),
        id='NZ_KB372811.1', name='NZ_KB372811.1',
        description='NZ_KB372811.1 Erwinia_toletana_TcdA1_3265660_3271807_backward', dbxrefs=[])}}

od = {'all': ['TcdA1', 'TcB_expanded', 'TcC_expanded']}

